### ISSUE TITLE
Utilizzo su Mac

### ISSUE THREAD

**Issue by forlando952** [AlessioScarfone/Digital-Signature-Chrome-Extension#1]
Come è possibile attivarlo su MAC?

**Comment by AlessioScarfone** [comment]
Ciao @forlando952 , ti ringrazio per l'interesse mostrato al mio lavoro ma, purtroppo non posso darti alcun supporto riguardo al funzionamento su macOS. L' estensione è stata sviluppata e testata solo su Windows.

In ogni caso, su Mac non potrai utilizzare lo [script di installazione](https://github.com/AlessioScarfone/Digital-Signature-Chrome-Extension/blob/master/hostapp-dist/install_host.bat) ma ti rimando alla documentazione [ufficiale di Google](https://developer.chrome.com/apps/nativeMessaging#native-messaging-host-location), dove potrai trovare i dettagli necessari per configurare il **Native Messaging** utilizzato dall'estensione.
