### ISSUE TITLE
Can I use it on MacOs?

### ISSUE THREAD

**Issue by markimpdl** [AlessioScarfone/Digital-Signature-Chrome-Extension#2]
Can I use it on MacOs?

**Comment by AlessioScarfone** [comment]
Hi @markimpdl ,
as reported in a previous issue (in italian) (https://github.com/AlessioScarfone/Digital-Signature-Chrome-Extension/issues/1#issuecomment-617876344), I have never tested on MacOs.

I think you can use it on macos but you won't be able to use the [installation script](https://github.com/AlessioScarfone/Digital-Signature-Chrome-Extension/blob/master/hostapp-dist/install_host.bat).  
You can follow the [official documentation](https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host-location)  to set up native messaging on you os.
